url: https://regularegg.github.io
baseurl: /regularegg.github.io
author: Mary L

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"



plugins:
  - jekyll-feed
  - jekyll-seo-tag
